In [1]:
"""
Imagine you have a magic arrow (vector) that, when you transform it (using a matrix), 
only gets longer or shorter but doesn’t change direction. This special arrow is called an eigenvector, 
and the factor by which it’s stretched or shrunk is the eigenvalue. 
For example, if you stretch a rubber band by a factor of 2, 
the direction of the band is the eigenvector, and 2 is the eigenvalue.
"""

'\nImagine you have a magic arrow (vector) that, when you transform it (using a matrix), \nonly gets longer or shorter but doesn’t change direction. This special arrow is called an eigenvector, \nand the factor by which it’s stretched or shrunk is the eigenvalue. \nFor example, if you stretch a rubber band by a factor of 2, \nthe direction of the band is the eigenvector, and 2 is the eigenvalue.\n'

In [1]:
import numpy as np

# Define a matrix (transformation)
A = np.array([[5, 2],
              [2, 5]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:")
print(A)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors (as columns):")
print(eigenvectors)

# Test the eigenvector/eigenvalue property: A * eigenvector = eigenvalue * eigenvector
first_eigenvector = eigenvectors[:, 0]  # First column is the first eigenvector
first_eigenvalue = eigenvalues[0]

# Multiply A with the first eigenvector
result_left = np.dot(A, first_eigenvector)
# Multiply eigenvalue with the first eigenvector
result_right = first_eigenvalue * first_eigenvector

print("\nTesting A * eigenvector == eigenvalue * eigenvector:")
print("A * eigenvector:", result_left)
print("eigenvalue * eigenvector:", result_right)

Matrix A:
[[5 2]
 [2 5]]

Eigenvalues: [7. 3.]
Eigenvectors (as columns):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Testing A * eigenvector == eigenvalue * eigenvector:
A * eigenvector: [4.94974747 4.94974747]
eigenvalue * eigenvector: [4.94974747 4.94974747]


In [4]:
"""
So you can see,

The matrix A transforms space.

The eigenvectors (columns of eigenvectors) are directions that don’t change when A is applied.

The eigenvalues (scalars) tell you how much each eigenvector is stretched.
"""

'\nSo you can see,\n\nThe matrix A transforms space.\n\nThe eigenvectors (columns of eigenvectors) are directions that don’t change when A is applied.\n\nThe eigenvalues (scalars) tell you how much each eigenvector is stretched.\n'

In [5]:
"""
Assignment for You:

1. Modify the Matrix: Change the matrix A to [[3, 1], [1, 3]] and rerun the code. 
What are the new eigenvalues and eigenvectors?

2. Verify Manually: Pick one eigenvector from the result and multiply it by A using pen-and-paper. 
Check if it equals the eigenvalue times the eigenvector.

3. Real-World Connection: Think of a scenario where finding these "special directions" (eigenvectors) 
might be useful (e.g., in computer graphics or physics).

"""

'\nAssignment for You:\n\n1. Modify the Matrix: Change the matrix A to [[3, 1], [1, 3]] and rerun the code. What are the new eigenvalues and eigenvectors?\n\n2. Verify Manually: Pick one eigenvector from the result and multiply it by A using pen-and-paper. Check if it equals the eigenvalue times the eigenvector.\n\n3. Real-World Connection: Think of a scenario where finding these "special directions" (eigenvectors) might be useful (e.g., in computer graphics or physics).\n\n'

In [2]:
import numpy as np

A = np.array([[3, 1],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:")
print(A)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors (as columns):")
print(eigenvectors)


first_eigenvector = eigenvectors[:, 0] 
first_eigenvalue = eigenvalues[0]


# Multiply A with the first eigenvector
result_left = np.dot(A, first_eigenvector)
# Multiply eigenvalue with the first eigenvector
result_right = first_eigenvalue * first_eigenvector

print("\nTesting A * eigenvector == eigenvalue * eigenvector:")
print("A * eigenvector:", result_left)
print("eigenvalue * eigenvector:", result_right)

Matrix A:
[[3 1]
 [1 3]]

Eigenvalues: [4. 2.]
Eigenvectors (as columns):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Testing A * eigenvector == eigenvalue * eigenvector:
A * eigenvector: [2.82842712 2.82842712]
eigenvalue * eigenvector: [2.82842712 2.82842712]


In [3]:
first_eigenvalue

4.0

In [4]:
first_eigenvector

array([0.70710678, 0.70710678])

In [5]:
0.70710678 * 4

2.82842712

In [ ]:
""" 
3. Real-World Connection: Think of a scenario where finding these "special directions" (eigenvectors) 
might be useful (e.g., in computer graphics or physics).

Answer:
Eigenvectors are used in Google's pagerank algorithm

"""